/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AgregarVuelos.java
 *
 * Created on Nov 23, 2013, 6:02:52 PM
 */
package view;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.consulta.Vuelo;
import model.persistencia.ConexionDB;
import model.persistencia.DataBaseManager;

/**
 *
 * @author camilortte
 */
public class AgregarVuelos extends javax.swing.JFrame {

    private Vuelo vuelo;
    
    /** Creates new form AgregarVuelos */
    public AgregarVuelos() {
        initComponents();
        rellenarCamposOrigenDestino();
    }

     public String getDiaSemana(Calendar fecha) {
        int dayOfWeek = fecha.get(Calendar.DAY_OF_WEEK);
        String dia = "";
        if (Calendar.MONDAY == dayOfWeek) {
            dia = "Lunes";
        } else if (Calendar.TUESDAY == dayOfWeek) {
            dia = "Martes";
        } else if (Calendar.WEDNESDAY == dayOfWeek) {
            dia = "Miercoles";
        } else if (Calendar.THURSDAY == dayOfWeek) {
            dia = "Jueves";
        } else if (Calendar.FRIDAY == dayOfWeek) {
            dia = "Viernes";
        } else if (Calendar.SATURDAY == dayOfWeek) {
            dia = "Sabado";
        } else if (Calendar.SUNDAY == dayOfWeek) {
            dia = "Domingo";
        }
        return dia;
    }
    
     private void rellenarCamposOrigenDestino(){
        try {
            ConexionDB con = new ConexionDB();
            DataBaseManager.getInstance().setConexionDB(con);
            Connection conexion=con.getConexion();
            Statement stat = conexion.createStatement();
            ResultSet rs = stat.executeQuery("select CIUD_nombre from ciudad,origen where CIUD_id=ORIG_CIUD_id");
            while(rs.next()){
                jComboBox_origen.addItem(rs.getString("CIUD_nombre"));
                jComboBox_destino.addItem(rs.getString("CIUD_nombre"));
            }            
        } catch (SQLException ex) {
            Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox_origen = new javax.swing.JComboBox();
        jComboBox_destino = new javax.swing.JComboBox();
        jMonthChooser_mes = new com.toedter.calendar.JMonthChooser();
        jYearChooser_anio = new com.toedter.calendar.JYearChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton_consultarFechas = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jComboBox_fechasPermitidas = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jComboBox_aerolinea = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jButton_agregarVuelo = new javax.swing.JButton();
        jLabel_costo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jComboBox_origen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_origenActionPerformed(evt);
            }
        });

        jComboBox_destino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_destinoActionPerformed(evt);
            }
        });

        jLabel1.setText("Origen");

        jLabel2.setText("Destino");

        jLabel3.setText("Fecha");

        jButton_consultarFechas.setText("Consultar posibles fechas");
        jButton_consultarFechas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_consultarFechasActionPerformed(evt);
            }
        });

        jLabel4.setText("Fechas permitidas");

        jLabel5.setText("Aerolinea");

        jComboBox_aerolinea.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Avianca", "Satena", "EasyFly", "Delta", "Aires" }));

        jLabel6.setText("Precio: ");

        jButton_agregarVuelo.setText("Agregar vuelo");
        jButton_agregarVuelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_agregarVueloActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_agregarVuelo, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                    .addComponent(jButton_consultarFechas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox_destino, javax.swing.GroupLayout.Alignment.TRAILING, 0, 295, Short.MAX_VALUE)
                            .addComponent(jComboBox_origen, javax.swing.GroupLayout.Alignment.TRAILING, 0, 295, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jYearChooser_anio, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                                .addComponent(jMonthChooser_mes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox_fechasPermitidas, javax.swing.GroupLayout.Alignment.TRAILING, 0, 230, Short.MAX_VALUE)
                            .addComponent(jComboBox_aerolinea, javax.swing.GroupLayout.Alignment.TRAILING, 0, 230, Short.MAX_VALUE)
                            .addComponent(jLabel_costo, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox_origen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox_destino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jYearChooser_anio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jMonthChooser_mes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_consultarFechas)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jComboBox_fechasPermitidas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jComboBox_aerolinea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel_costo))
                .addGap(18, 27, Short.MAX_VALUE)
                .addComponent(jButton_agregarVuelo)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jButton_consultarFechasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_consultarFechasActionPerformed
    jComboBox_fechasPermitidas.removeAllItems();
    vuelo=new Vuelo(this.jComboBox_origen.getSelectedItem().toString(), 
            this.jComboBox_destino.getSelectedItem().toString(),
            "", null, null,0.0);
    
    Calendar calendar=Calendar.getInstance();
    //JOptionPane.showMessageDialog(null, String.valueOf(jMonthChooser_mes.getMonth()),"NOne",JOptionPane.ERROR_MESSAGE);
    calendar.set(jYearChooser_anio.getYear(), jMonthChooser_mes.getMonth(), 1);    
    ArrayList<String> fechas=vuelo.agregarVuelo(calendar, jComboBox_origen.getSelectedItem().toString(),
            jComboBox_destino.getSelectedItem().toString());
    
    for (int i = 0; i < fechas.size(); i++) {
        jComboBox_fechasPermitidas.addItem(fechas.get(i));
    }
    
    Double costo=DataBaseManager.getInstance().getCostoVuelo(
                jComboBox_aerolinea.getSelectedItem().toString());
    jLabel_costo.setText(costo.toString());
}//GEN-LAST:event_jButton_consultarFechasActionPerformed

private void jButton_agregarVueloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_agregarVueloActionPerformed
    if(jComboBox_fechasPermitidas.getItemCount()<=0){
        JOptionPane.showMessageDialog(this, "Debe seleccionar una fecha","Error Sin fecha", JOptionPane.ERROR_MESSAGE);
    }else{  
        //Obtenemos las fechas
        String fecha=jComboBox_fechasPermitidas.getSelectedItem().toString();
        int year=Integer.parseInt(fecha.substring(0, fecha.indexOf("-")));
        System.out.println("Year="+year);
        fecha=fecha.substring(fecha.indexOf("-")+1, fecha.length());
        System.out.println("Fecha="+fecha);
        int month=Integer.parseInt(fecha.substring(0, fecha.indexOf("-")));
        System.out.println("Mint="+month);
        fecha=fecha.substring(fecha.indexOf("-")+1, fecha.length());
        int day=Integer.parseInt(fecha);
        
        //Si la fecha es un sabado o un domingo
        Calendar calendar=Calendar.getInstance();
        calendar.set(year, month-1, day);
        
        Double costo=DataBaseManager.getInstance().getCostoVuelo(
                jComboBox_aerolinea.getSelectedItem().toString());
        String dia_seman=getDiaSemana(calendar);        
        if(dia_seman.compareTo("Domingo")==0 || dia_seman.compareTo("Sabado")==0){
            costo=costo+(costo*0.1);
        }        
        DataBaseManager.getInstance().insertarVuelo(
                jComboBox_origen.getSelectedItem().toString(),
                jComboBox_destino.getSelectedItem().toString(),
                jComboBox_fechasPermitidas.getSelectedItem().toString(), 
                jComboBox_aerolinea.getSelectedItem().toString(),
                costo.toString());  
               
    }
}//GEN-LAST:event_jButton_agregarVueloActionPerformed

private void jComboBox_origenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_origenActionPerformed
    jComboBox_fechasPermitidas.removeAllItems();
}//GEN-LAST:event_jComboBox_origenActionPerformed

private void jComboBox_destinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_destinoActionPerformed
    jComboBox_fechasPermitidas.removeAllItems();
}//GEN-LAST:event_jComboBox_destinoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarVuelos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarVuelos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarVuelos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarVuelos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new AgregarVuelos().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_agregarVuelo;
    private javax.swing.JButton jButton_consultarFechas;
    private javax.swing.JComboBox jComboBox_aerolinea;
    private javax.swing.JComboBox jComboBox_destino;
    private javax.swing.JComboBox jComboBox_fechasPermitidas;
    private javax.swing.JComboBox jComboBox_origen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel_costo;
    private com.toedter.calendar.JMonthChooser jMonthChooser_mes;
    private com.toedter.calendar.JYearChooser jYearChooser_anio;
    // End of variables declaration//GEN-END:variables
}
