/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import javax.swing.JOptionPane;
import model.persistencia.DataBaseManager;
import org.openstreetmap.gui.jmapviewer.Coordinate;
import org.openstreetmap.gui.jmapviewer.MapMarkerDot;
import org.openstreetmap.gui.jmapviewer.MapPolygonImpl;

/**
 *
 * @author camilortte
 */
public class ConsultaVuelosFrame extends javax.swing.JFrame {

    /**
     * Creates new form ConsultaVuelosFrame
     */
    public ConsultaVuelosFrame() {
        initComponents();
         jMapViewer1.setDisplayPositionByLatLon(4.625704, -74.100466, 5);
        String sql="select ciud_nombre, ciud_latitud, ciud_longitud from ciudad";
        actualizarCiudadesEnJMapViewer(DataBaseManager.getInstance().consultarArray(sql));
        rellenarCamposCiudades();
        setLocationRelativeTo(null);
        
    }
    
    
    private void rellenarCamposCiudades(){
        
        ArrayList<ArrayList<String>> ciudades=DataBaseManager.getInstance().consultarArray("Select ciud_nombre from ciudad");
        int i=0;
        for(ArrayList<String> ciudad: ciudades){
            if(i==0){}else{
                jComboBox_ciudades.addItem(ciudad.get(0));
            }
            i++;
        }
        
        
    }
    
    private void actualizarCiudadesEnJMapViewer(ArrayList<ArrayList<String>> ciudades){
        for(ArrayList<String> ciudad: ciudades){
            MapMarkerDot mp=new MapMarkerDot(Double.parseDouble(ciudad.get(1)),
                    Double.parseDouble(ciudad.get(2)));
            mp.setName(ciudad.get(0));
            jMapViewer1.addMapMarker(mp);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMapViewer1 = new org.openstreetmap.gui.jmapviewer.JMapViewer();
        jLabel1 = new javax.swing.JLabel();
        jComboBox_ciudades = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consulta");

        jLabel1.setText("Selecciona la ciudad a consultar");

        jComboBox_ciudades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_ciudadesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jMapViewer1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox_ciudades, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 244, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox_ciudades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jMapViewer1, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox_ciudadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_ciudadesActionPerformed
        ArrayList<ArrayList<String>> ciudades=DataBaseManager.getInstance().
                getDestinosCiudad((String) this.jComboBox_ciudades.getSelectedItem());
        String latlon[]=DataBaseManager.getInstance().getLotLanCiudad((String) this.jComboBox_ciudades.getSelectedItem());
        Coordinate coordenadasOrigen=new Coordinate(Double.parseDouble(latlon[0]),
                Double.parseDouble(latlon[1]));
        jMapViewer1.removeAllMapPolygons();
        try{
            for(ArrayList<String> ciudad_array:ciudades){
                MapMarkerDot mp=new MapMarkerDot(Double.parseDouble(ciudad_array.get(1)),
                        Double.parseDouble(ciudad_array.get(2)));
                mp.setName(ciudad_array.get(0));
                jMapViewer1.addMapMarker(mp);


                List<Coordinate> route = new ArrayList<Coordinate>
                        (Arrays.asList(coordenadasOrigen, mp.getCoordinate(), mp.getCoordinate()));
                this.jMapViewer1.addMapPolygon(new MapPolygonImpl(route));

            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "No hay destinos para este origen","Error",JOptionPane.ERROR_MESSAGE);
        }
        
        
    }//GEN-LAST:event_jComboBox_ciudadesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultaVuelosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultaVuelosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultaVuelosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaVuelosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultaVuelosFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBox_ciudades;
    private javax.swing.JLabel jLabel1;
    private org.openstreetmap.gui.jmapviewer.JMapViewer jMapViewer1;
    // End of variables declaration//GEN-END:variables
}
